### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Micromic0** [nathangur/Teardown-Boundary-Remover#1]
When I press f8 nothing happens. I tried pressing it in the main menu, while the level is loading, and while I'm in the level. Nothing happens, I'm on the latest (1.5.0) version.

**Comment by nathangur** [comment]
The new update broke it. I will fix it soon!

**Comment by nathangur** [comment]
Updated to latest version : 1.5.1

**Comment by Micromic0** [comment]
Thanks, I'm going to test it tomorrow!

**Comment by nathangur** [comment]
> Thanks, I'm going to test it tomorrow!

Let me know if it works!

**Comment by Micromic0** [comment]
> > Thanks, I'm going to test it tomorrow!
> 
> Let me know if it works!

actually I just tested it, it doesn't seem to work. I tested it on a map called "Russian town 3
" unless it is supposed to work on some maps and not all?

**Comment by nathangur** [comment]
> > > Thanks, I'm going to test it tomorrow!
> > 
> > 
> > Let me know if it works!
> 
> actually I just tested it, it doesn't seem to work. I tested it on a map called "Russian town 3 " unless it is supposed to work on some maps and not all?

It should work on all maps and I've tested on two different clean game installs and it works fine. Try it on Lee Chemicals just to be sure it works. After pressing f8, do you see anything in the console window? make sure you are properly pressing f8 and not using the windows functions instead.

**Comment by Micromic0** [comment]
windows functions? I just press f8 on my keyboard, am I supposed to press it with something else? I tried it on lee chemicals, still doesn't work.

**Comment by nathangur** [comment]
What does the console window say after you press f8?

Try both pressing the button f8 and holding the fn key and pressing f8.

**Comment by Micromic0** [comment]
tried both of your variants on lee, still doesn't work, nothing in the console. Can it maybe be a mod related thing?

**Comment by nathangur** [comment]
Are you in the TD discord? If so, could we hop on a call so I can see this happen? I have no clue why this wouldn't work since it's fine here.

**Comment by nathangur** [comment]
https://github.com/nathangur/Teardown-Boundary-Remover/releases/tag/test

Here, try this one. I've packaged up the dependencies with the dll in a different way, so hopefully it might work?

**Comment by Micromic0** [comment]
just tried it, still doesn't seem to work even with all of the mods off. I am also on teardown's discord, but sadly my mic doesn't work

**Comment by dareksan3KY** [comment]
solution founded by myself, just rename winmm.dll to dxgi.dll

**Comment by Micromic0** [comment]
> solution founded by myself, just rename winmm.dll to dxgi.dll

what version are you talking about: about the test version or the 1.5.1 version?

**Comment by nathangur** [comment]
> solution founded by myself, just rename winmm.dll to dxgi.dll

Interesting. Both work on my end but I'll upload as dxgi.dll from now on. 

Also I will be posting an update for 1.5.2 tomorrow

**Comment by nathangur** [comment]
1.5.2 is out!

**Comment by Micromic0** [comment]
I renamed it to dxgi.dll and it works now, but a console window pops up when you start teardown saying "dll proxy" that is supposed to happen, right?

**Comment by nathangur** [comment]
> I renamed it to dxgi.dll and it works now, but a console window pops up when you start teardown saying "dll proxy" that is supposed to happen, right?

Yes.

**Comment by Micromic0** [comment]
alright, thanks!

**Comment by Micromic0** [comment]
alright, thanks!
